### ISSUE TITLE
Handle location of the IMU in iCub Head v2 COM Express 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-models-generator#110]
For all the models generated by the generator, we should make sure that we export the correct location of the IMU if they are using an iCub Head v2 COM Express . 

See https://github.com/robotology/icub-main/issues/285 .

**Comment by traversaro** [comment]
The `DH`-generated models simply need to be updated, period. For the SimMechanics generated model, which IMU are we using to generate the simplified model in the CAD @fiorisi ?

**Comment by traversaro** [comment]
@fiorisi do you think we can recover the information of whether the model https://github.com/icub-tech-iit/cad-mechanics-public/blob/master/projects/simulation_model/icub1_icub2/icub_2-5_bb_sim_model.asm.1 was generated with the XSens IMU or the bno055 IMU in the head? Thanks!

**Comment by fiorisi** [comment]
The IMU frame in the current iCub2.5 model was coming from the iCUb2 head (see [this report](https://github.com/robotology/icub-models-generator/blob/master/simmechanics/data/icub2_5/ConversionProcess.xlsx) ).

In this **obsolete** head there was a board named `ATMEL_BNO055_XPLAINED_PRO` which contained a bno055.
![image](https://user-images.githubusercontent.com/8970230/99065345-8ec56780-25a7-11eb-9a01-1adee1a1622a.png)


We have to regenerate the head files also for the iCUb2.5 URDF model.

**Comment by traversaro** [comment]
Actually the bno055 is indeed the one that is installed in the few iCub2.5 I am aware of, so that seems to be correct to me and coherent with what we have in icub-main's iKin classes. The more recent RFE board was only added as part of iCub 2.6 (see https://icub-tech-iit.github.io/documentation/icub_versions/) and for the time being we handled that in https://github.com/robotology/icub-models-generator/pull/164 by just moving the IMU frame, but if at some point we generate new Sim Mechanics files for the latest iCub 2.7 model it would be nice, but it is not blocking anything.
