### ISSUE TITLE
Rename repo to  icub-models-generator

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-models-generator#168]
As the generate model is icub-model**s**, I think this repo should be called icub-model**s**-generator. It is a stupid thing, but I am spending 10 seconds to think about it everytime I open the repo, so in the long run changing its name will save my time. : ) 

Any objection? 
cc @Nicogene @S-Dafarra @prashanthr05

**Comment by S-Dafarra** [comment]
No objection from me

**Comment by Nicogene** [comment]
My OCD `loves` it

**Comment by prashanthr05** [comment]
Let's kill it before it kills us. :D

**Comment by traversaro** [comment]
Done.
