### ISSUE TITLE
The test does not compile after iDynTree release

### ISSUE THREAD

**Issue by diegoferigo** [robotology/icub-models-generator#177]
In particular, this method has been removed:

https://github.com/robotology/icub-models-generator/blob/e8e255a822a41d32c94aec30b5d3b1eef021af3d/tests/icub-model-test.cpp#L359-L362

cc @traversaro

**Comment by traversaro** [comment]
Thanks for the feedback.

**Comment by GiulioRomualdi** [comment]
fixed by #178
