### ISSUE TITLE
Define how to handle the models of iCub with the fake battery

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-models-generator#196]
The version of iCub with the battery pack is 2.5.5 (see https://icub-tech-iit.github.io/documentation/icub_versions/) but some iCub with a backpack has a "fake" battery that has a different weight with respect to the real one.

We should handle also the "fake battery" case.

**Comment by traversaro** [comment]
All the robots that have a "fake battery", the "fake battery" has the same mass of the real battery, so from the model point of view we can consider the robot with a "fake battery" and the robot with a "real battery" as the same. Furthermore, as of 2021/03/30 the only iCub robot with a real battery is the iCubGenova04, so this is the exception and that has been noted in the Notes section in https://robot-bazaar.iit.it/robots/collection/robots/iCubGenova04 .
