### ISSUE TITLE
Increase the damping of iCubGazebov3 and the PID gains

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-models-generator#197]
The damping is currently set ot 0.06 for all the joints. This value is very small, also considering the real robot. After some tests, ``2.0`` seems a more reasonable value.

Regarding the PID, I used the following values  P 40.0  I 0.35  D 0.35 on all the joints, and seemed to be working fine, at least for 
the walking.

I can also prepare a PR if you point me to the correct files to modify.

cc @Nicogene @traversaro

**Comment by Nicogene** [comment]
Hi @S-Dafarra !

The damping can be specified in the csv (e.g. https://github.com/robotology/icub-models-generator/blob/master/simmechanics/data/icub3/ICUB_3_joint_all_parameters.csv)
And the PID can be changed in all the control board ini files (see https://github.com/robotology/icub-models-generator/blob/20a9bbcfa6e962c44be22a30c531724a0227fb7e/simmechanics/data/icub3/conf/gazebo_icub_torso.ini#L40-L42 for example)

A PR is more than welcome, just remember to change all the csv files here https://github.com/robotology/icub-models-generator/tree/master/simmechanics/data/icub3, for now we are using the one with all the joints in one, but in the future we would follow the modular approach

**Comment by traversaro** [comment]
> A PR is more than welcome, just remember to change all the csv files here https://github.com/robotology/icub-models-generator/tree/master/simmechanics/data/icub3, for now we are using the one with all the joints in one, but in the future we would follow the modular approach

Can't we just delete the redundant one, and once we want to go for the modular approach we take the all joint one and decompose it in the separate one? Trying to maintain two different ["non"-single sources of true](https://en.wikipedia.org/wiki/Single_source_of_truth) it tricky.

**Comment by Nicogene** [comment]
> Can't we just delete the redundant one, and once we want to go for the modular approach we take the all joint one and decompose it in the separate one? Trying to maintain two different "non"-single sources of true it tricky.

I am afraid that it is not yet possible because the csv it taken by the `simmechanics-to-urdf` script with the simmechanics XML and for now we have not all the modular simmechanics XMLs and we do not know how to assemble the resulting urdfs.

Or it is possible to pass to the script more than one csv??

**Comment by traversaro** [comment]
> 
> 
> > Can't we just delete the redundant one, and once we want to go for the modular approach we take the all joint one and decompose it in the separate one? Trying to maintain two different "non"-single sources of true it tricky.
> 
> I am afraid that it is not yet possible because the csv it taken by the `simmechanics-to-urdf` script with the simmechanics XML and for now we have not all the modular simmechanics XMLs and we do not know how to assemble the resulting urdfs.
> 
> Or it is possible to pass to the script more than one csv??

Sorry, I meant to delete the modular one, as those are the one that are the moment are not used.

**Comment by Nicogene** [comment]
> Sorry, I meant to delete the modular one, as those are the one that are the moment are not used. In any case, this is not a big priority.

Yeah we can restore them later if necessary

**Comment by S-Dafarra** [comment]
So the final verdict? I can remove them if you want, less files to edit :grin:

**Comment by traversaro** [comment]
> 
> 
> So the final verdict? I can remove them if you want, less files to edit 😁

Let's remove them!

**Comment by traversaro** [comment]
Because it seems that `ICUB3_L_LEG_SIM_MODEL.xml`, `ICUB3_R_LEG_SIM_MODEL.xml` and `ICUB3_UPPERBODY_SIM_MODEL.xml` are already lagging behind w.r.t. to `ICUB3_ALL_SIM_MODEL.xml`, so better to remove them before creating more confusion.

**Comment by S-Dafarra** [comment]
I have noticed those files are reference here: https://github.com/robotology/icub-models-generator/blob/20a9bbcfa6e962c44be22a30c531724a0227fb7e/simmechanics/data/icub3/convertModel.sh#L1-L12

Should I also comment out those lines?
