### ISSUE TITLE
Investigate on how to fix the colors in the urdf models

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-models-generator#216]
Thanks to https://github.com/robotology/idyntree/pull/961 it will be possible to display the icub models with the colors defined in the `urdf` files.

I noticed that the robot colors are "randomly" chosen when the model is generated. As a consequence, the representation of the model is a bit bizarre

![image](https://user-images.githubusercontent.com/16744101/151455326-373165cb-f31d-4a6e-8bef-69d5fb5cc97d.png)

This is  how TALOS is loaded by the very same visualizer 

![](https://user-images.githubusercontent.com/16744101/151451889-e147a9e2-dd9b-466e-82ff-8ac8d6af4c2c.png)

 
Do you think it's possible to fix the color of the links?

cc @traversaro

**Comment by GiulioRomualdi** [comment]
I think it's related to this: https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L24-L28

**Comment by traversaro** [comment]
Yes, we can: 
* Modify `simmechanics-to-urdf` (just to set a user-specify color with an option, or just remove the random color behaviour), and switch icub-model-generator to use the new version of simmechanics-to-urdf
or:
* Create a script (probably in python as it is easier) that sets all the colors in a given URDF to a user-specified color, and run that on the icub models in the icub-model-generator CI

Both options are fine for me. We also need to identify which color we want to use.

**Comment by GiulioRomualdi** [comment]
> Note that simmechanics-to-urdf already have a similar option (see https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L1116), but that would require to add a line in the yaml for each link to set a different color, so it may not be super-convenient.

I actually noticed that this dictionary is filled by the `xml` file and not by the yaml file: [From here](https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L228) -> [here](https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L569) -> [finally here](https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L593-L614)

As far as I understood the `xml` file is generated by simmechanics and it cannot be modified. 

Should I replicate the same logic for the `yaml` file?

**Comment by traversaro** [comment]
> > Note that simmechanics-to-urdf already have a similar option (see https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L1116), but that would require to add a line in the yaml for each link to set a different color, so it may not be super-convenient.
> 
> I actually noticed that this dictionary is filled by the `xml` file and not by the yaml file: [From here](https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L228) -> [here](https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L569) -> [finally here](https://github.com/robotology/simmechanics-to-urdf/blob/f6055ab8d627c45138ddde46532ea42a74b48caa/simmechanics_to_urdf/firstgen.py#L593-L614)
> 
> As far as I understood the `xml` file is generated by simmechanics and it cannot be modified.

You are right, I misunderstood the code. 

> Should I replicate the same logic for the `yaml` file?

I guess not, until we have a need for it.

**Comment by GiulioRomualdi** [comment]
https://github.com/robotology/icub-models-generator/pull/217 attempts to close this issue
