### ISSUE TITLE
The meshes of icub3 seems not compatible with rviz2

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-models-generator#229]
When trying to visualize the icub3 meshes on `rviz2` i got these errors:

```
[ERROR] [1670425894.974567837] [rviz2]: The STL file 'package://iCub/meshes/simmechanics/sim_icub3_torso_2_prt.stl' is malformed. It starts with the word 'solid' and also contains the word 'endsolid', indicating that it's an ASCII STL file, but rviz can only load binary STL files so it will not be loaded. Please convert it to a binary STL file.
```

`ros2 pkg list | grep iCub` works fine.

cc @pattacini @traversaro

**Comment by Nicogene** [comment]
Exporting as binary seems to work thanks!

![immagine](https://user-images.githubusercontent.com/19152494/206235708-9c2ccf1d-b438-4516-9477-cfdf5b3cf2f8.png)

**Comment by traversaro** [comment]
Should we update the Creo 2 URDF guide with this indication? The guide should be at https://github.com/icub-tech-iit/cad-mechanics-public/wiki/Creo-mechanism-to-URDF (see http://wiki.icub.org/wiki/Creo_Mechanism_to_URDF), but I can't find it anymore.

**Comment by Nicogene** [comment]
@traversaro the guide has been moved [here](https://github.com/icub-tech-iit/cad-libraries/wiki/Prepare-PTC-Creo-Mechanism-for-URDF)

**Comment by traversaro** [comment]
Related RViz issues:
* https://github.com/ros2/rviz/issues/712
* https://github.com/ros-visualization/rviz/pull/1365

**Comment by fiorisi** [comment]
> For the future we should make sure that at some point in the model generation pipeline (either before or after the files are committed in this repo) the stl files should be converted from ascii to binary.

I will investigate if the [Simscape Multibody Link](https://www.mathworks.com/help/smlink/ref/linking-and-unlinking-simmechanics-link-software-with-proengineer.html) allows to set the `.stl` generation with the `binary` option.

**Comment by Nicogene** [comment]
Here is a simple script for converting the stl: https://github.com/cmpolis/convertSTL

It seems to work fine, shall we include it in our pipeline of urdf generation?

**Comment by traversaro** [comment]
> Here is a simple script for converting the stl: https://github.com/cmpolis/convertSTL
> 
> It seems to work fine, shall we include it in our pipeline of urdf generation?

Ok for me.
