### ISSUE TITLE
iCubGazeboV2_7: xsens root_link IMU not published correctly

### ISSUE THREAD

**Issue by martinaxgloria** [robotology/icub-models-generator#245]
The model `iCubGazeboV2_7` returns some errors when the model is imported into Gazebo. I attach here the log:

- [iCubGazeboV2_7.log](https://github.com/robotology/icub-models-generator/files/12237476/iCubGazeboV2_7.log)

This error doesn't cause the yarprobotinterface close, so it is not blocking, but it is something to be investigated due to the fact that, for example, with iCubGazeboV2_5 I didn't retrieve any error. 

- [iCubGazeboV2_5.log](https://github.com/robotology/icub-models-generator/files/12237519/iCubGazeboV2_5.log)

For the sake of completeness, I'm using the last distro `v2023.05.02`

cc @traversaro @pattacini

**Comment by pattacini** [comment]
For completeness, I've also tested `iCubGazeboV2_6` and it seems running as good as `iCubGazeboV2_5`:
- [iCubGazeboV2_6.log](https://github.com/robotology/icub-models-generator/files/12237699/iCubGazeboV2_6.log)
